import { test } from 'node:test';
import assert from 'node:assert/strict';
import { extractSystem, extractChrome } from '../build/lib.mjs';

const SHEET = [
  '  :root {',
  '    /* build:tokens */',
  '    --a: 1px;',
  '/* /build:tokens */',
  '    /* documentation chrome · light. Dark redefines these names only. */',
  '    --doc-bg: var(--a);',
  '  }',
  '  body { background: var(--doc-bg); }',
  '  .d-mast { color: red; }',
  '  /* ==========================================================',
  '     2. Grounds. A ground sets the variables that components',
  '     ========================================================== */',
  '  .g { background: var(--g-bg); }',
  '  /* ==========================================================',
  '     3. Components. Class names are the canonical names.',
  '     ========================================================== */',
  '  .btn { padding: var(--space-2); }',
  '  /* ---------- foundations specimens ---------- */',
  '  .swatch { height: 8px; }',
].join('\n');

test('extractSystem holds the tokens, the grounds, and the components, and no chrome or specimen rule', () => {
  const css = extractSystem(SHEET, ':root {\n  --a: 1px;\n}\n', '9.9.9', '2026-01-01');
  assert.match(css, /^\/\* Cristian Vega 9\.9\.9 · 2026-01-01 · generated by npm run build; do not edit \*\/\n/);
  assert.match(css, /--a: 1px;/);
  assert.match(css, /\.g \{ background: var\(--g-bg\); \}/);
  assert.match(css, /\.btn \{ padding: var\(--space-2\); \}/);
  assert.doesNotMatch(css, /\.d-mast/);
  assert.doesNotMatch(css, /\.swatch/);
});

test('extractChrome holds the documentation tokens, the base rules, and the furniture, and no ground or component rule', () => {
  const css = extractChrome(SHEET, '9.9.9', '2026-01-01');
  assert.match(css, /^\/\* Cristian Vega 9\.9\.9 · 2026-01-01 · generated by npm run build; do not edit \*\/\n/);
  assert.match(css, /--doc-bg: var\(--a\);/);
  assert.match(css, /body \{ background: var\(--doc-bg\); \}/);
  assert.match(css, /\.d-mast \{ color: red; \}/);
  assert.doesNotMatch(css, /\.g \{/);
  assert.doesNotMatch(css, /\.btn \{/);
});

test('extractSystem fails loudly when an anchor is missing', () => {
  assert.throws(() => extractSystem('  .g { background: red; }', '', '9.9.9', '2026-01-01'), /2\. Grounds/);
});

test('extractSystem and extractChrome emit balanced braces', () => {
  const system = extractSystem(SHEET, ':root {\n  --a: 1px;\n}\n', '9.9.9', '2026-01-01');
  const chrome = extractChrome(SHEET, '9.9.9', '2026-01-01');
  for (const css of [system, chrome]) {
    const opens = (css.match(/\{/g) || []).length;
    const closes = (css.match(/\}/g) || []).length;
    assert.equal(opens, closes, `unbalanced braces: ${opens} open, ${closes} close`);
  }
});
